"""empty message

Revision ID: 03ea99db9bc8
Revises: f3243404dd8e
Create Date: 2025-05-01 00:26:22.990711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ea99db9bc8'
down_revision = 'f3243404dd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_type_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_type_fkey', 'user', ['type'], ['id'])

    # ### end Alembic commands ###
